-- --------------------------------------------------------
-- Host:                         localhost
-- Versión del servidor:         5.7.19 - MySQL Community Server (GPL)
-- SO del servidor:              Win64
-- HeidiSQL Versión:             9.4.0.5125
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Volcando estructura de base de datos para gym
CREATE DATABASE IF NOT EXISTS `gym` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci */;
USE `gym`;

-- Volcando estructura para tabla gym.ejercicios
CREATE TABLE IF NOT EXISTS `ejercicios` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `id_grupo` int(10) unsigned NOT NULL,
  `ejercicio` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `imagen` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `explicacion` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tiempo` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `material` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `posicion` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `consejo` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ejercicios_id_grupo_foreign` (`id_grupo`),
  CONSTRAINT `ejercicios_id_grupo_foreign` FOREIGN KEY (`id_grupo`) REFERENCES `grupos` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=203 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla gym.ejercicios: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ejercicios` DISABLE KEYS */;
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(1, 1, 'abdominales banco multipower', 'abdominales/abdominales_banco_multipower.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(2, 1, 'abdominales modo flexión', 'abdominales/abdominales_como_flexiones.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(3, 1, 'abdominales con banco', 'abdominales/abdominales_con_banco.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(4, 1, 'abdominales con remo', 'abdominales/abdominales_con_remo.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(5, 1, 'abdominales cuadriceps', 'abdominales/abdominales_cuadriceps.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(6, 1, 'abdominales inferior', 'abdominales/abdominales_inferiro.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(7, 1, 'abdominales máquina', 'abdominales/abdominales_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(8, 1, 'abdominales pies elevados', 'abdominales/abdominales_pies_elebados.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(9, 1, 'abdominales polea', 'abdominales/abdominales_polea.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(10, 1, 'abdominales polea triceps', 'abdominales/abdominales_polea_triceps.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(11, 1, 'abdominales superior', 'abdominales/abdominales_superior.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(12, 1, 'oblicuos', 'abdominales/oblicuos.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(13, 1, 'oblicuos press banca', 'abdominales/oblicuos_pres_banca.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(14, 1, 'oblicuos tradicional', 'abdominales/oblicuos_tradicional.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(15, 2, 'curl biceps', 'biceps/curl_biceps.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(16, 2, 'curl biceps abierto', 'biceps/curl_biceps_aberto.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(17, 2, 'curl biceps máquina', 'biceps/curl_biceps_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(18, 2, 'curl biceps polea', 'biceps/curl_biceps_polea.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(19, 2, 'curl concentrado', 'biceps/curl_concentrado.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(76, 2, 'curl concentrado cerrado', 'biceps/curl_concentrado_cerrado.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(77, 2, 'curl concentrado depie', 'biceps/curl_concentrado_depie.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(78, 2, 'curl concentrado maquina', 'biceps/curl_concentrado_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(79, 2, 'curl concentrado multiPower', 'biceps/curl_concentrado_multiPower.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(80, 2, 'curl concentrado multiPower abierto', 'biceps/curl_concentrado_multiPower_abierto.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(81, 2, 'curl concentrado rodila', 'biceps/curl_concentrado_rodila.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(82, 2, 'curl con mancuernas', 'biceps/curl_con_mancuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(83, 2, 'curl con polea', 'biceps/curl_con_polea.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(84, 2, 'curl con polea barra recta', 'biceps/curl_con_polea_barra_recta.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(85, 2, 'curl estiramiento', 'biceps/curl_estiramiento.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(86, 2, 'curl martillo', 'biceps/curl_martillo.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(87, 2, 'curl martillo de pie', 'biceps/curl_martillo_depie.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(88, 3, 'triceps concentrado maquina', 'triceps/triceps_concentrado_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(89, 3, 'triceps concentrado maquina barra v', 'triceps/triceps_concentrado_maquina_barra_v.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(90, 3, 'triceps concentrado maquina un brazo', 'triceps/triceps_concentrado_maquina_un_brazo.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(91, 3, 'triceps fondos entre bancos', 'triceps/triceps_fondos_entre_bancos.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(92, 3, 'triceps fondos maquina', 'triceps/triceps_fondos_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(93, 3, 'triceps pajaritos', 'triceps/triceps_pajaritos.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(94, 3, 'triceps pajaritos un brazo', 'triceps/triceps_pajaritos_un_brazo.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(95, 3, 'triceps presbanca', 'triceps/triceps_presbanca.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(96, 3, 'triceps presbanca dos mancuernas', 'triceps/triceps_presbanca_dos_mancuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(97, 3, 'triceps presbanca multipower', 'triceps/triceps_presbanca_multipower.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(98, 3, 'triceps sentado dos brazos una mancuerna', 'triceps/triceps_sentado_dos_brazos_una_mancuerna.p', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(99, 3, 'triceps sentado un brazos una mancuerna', 'triceps/triceps_sentado_un_brazos_una_mancuerna.pn', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(100, 4, 'espalda banco', 'espalda/espalda_banco.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(101, 4, 'espalda barra multipower', 'espalda/espalda_barra_multipower.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(102, 4, 'espalda biceps polea', 'espalda/espalda_biceps_polea.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(103, 4, 'espalda discos', 'espalda/espalda_discos.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(104, 4, 'espalda dominadas', 'espalda/espalda_dominadas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(105, 4, 'espalda dominadas maquina', 'espalda/espalda_dominadas_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(106, 4, 'espalda exterior barra multipower', 'espalda/espalda_exterior_barra_multipower.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(107, 4, 'espalda mancuernas', 'espalda/espalda_mancuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(108, 4, 'espalda polea brazos estirados', 'espalda/espalda_polea_brazos_estirados.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(109, 4, 'espalda polea delante', 'espalda/espalda_polea_delante.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(110, 4, 'espalda polea detras', 'espalda/espalda_polea_detras.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(111, 4, 'espalda remo cerrado', 'espalda/espalda_remo_cerrado.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(112, 5, 'Hombro', 'hombros/Hombro.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(113, 5, 'Hombro aperturas', 'hombros/Hombro_aperturas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(114, 5, 'Hombro aperturas banco lateral', 'hombros/Hombro_aperturas_banco_lateral.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(115, 5, 'Hombro aperturas inclinado', 'hombros/Hombro_aperturas_inclinado.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(116, 5, 'Hombro aperturas polea', 'hombros/Hombro_aperturas_polea.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(117, 5, 'Hombro deltoides', 'hombros/Hombro_deltoides.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(118, 5, 'Hombro deltoides mancuernas', 'hombros/Hombro_deltoides_mancuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(119, 5, 'Hombro deltoides maquina', 'hombros/Hombro_deltoides_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(120, 5, 'Hombro elebaciones', 'hombros/Hombro_elebaciones.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(121, 5, 'Hombro elebaciones polea', 'hombros/Hombro_elebaciones_polea.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(122, 5, 'Hombro elebaciones una a una', 'hombros/Hombro_elebaciones_una_a_una.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(123, 5, 'Hombro pajaritos', 'hombros/Hombro_pajaritos.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(125, 5, 'Hombro aperturas', 'hombros/Hombro_aperturas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(126, 5, 'Hombro aperturas banco lateral', 'hombros/Hombro_aperturas_banco_lateral.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(127, 5, 'Hombro aperturas inclinado', 'hombros/Hombro_aperturas_inclinado.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(128, 5, 'Hombro aperturas polea', 'hombros/Hombro_aperturas_polea.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(129, 5, 'Hombro deltoides', 'hombros/Hombro_deltoides.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(130, 5, 'Hombro deltoides mancuernas', 'hombros/Hombro_deltoides_mancuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(131, 5, 'Hombro deltoides maquina', 'hombros/Hombro_deltoides_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(132, 5, 'Hombro elebaciones', 'hombros/Hombro_elebaciones.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(133, 5, 'Hombro elebaciones polea', 'hombros/Hombro_elebaciones_polea.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(134, 5, 'Hombro elebaciones una a una', 'hombros/Hombro_elebaciones_una_a_una.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(136, 6, 'pecho aperturas', 'pecho/pecho_aperturas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(137, 6, 'pecho aperturas mancuernas', 'pecho/pecho_aperturas_mancuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(138, 6, 'pecho aperturas maquina', 'pecho/pecho_aperturas_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(139, 6, 'pecho aperturas poleas', 'pecho/pecho_aperturas_poleas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(140, 6, 'pecho concentrado', 'pecho/pecho_concentrado.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(141, 6, 'pecho dominadas', 'pecho/pecho_dominadas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(142, 6, 'pecho flexiones', 'pecho/pecho_flexiones.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(143, 6, 'pecho inclinado mancuernas', 'pecho/pecho_inclinado_mancuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(144, 6, 'pecho inclinado polea', 'pecho/pecho_inclinado_polea.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(145, 6, 'pecho maquina', 'pecho/pecho_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(146, 6, 'pecho maquina concentrado', 'pecho/pecho_maquina_concentrado.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(147, 6, 'pecho pesolibre', 'pecho/pecho_pesolibre.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(148, 6, 'pecho peso frances', 'pecho/pecho_peso_frances.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(149, 6, 'pecho poleas', 'pecho/pecho_poleas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(150, 6, 'pecho presbanca', 'pecho/pecho_presbanca.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(151, 6, 'pecho presbanca inclinado mancuernas', 'pecho/pecho_presbanca_inclinado_mancuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(152, 6, 'pecho presbanca mancuernas', 'pecho/pecho_presbanca_mancuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(153, 6, 'pecho pres banca inclinado', 'pecho/pecho_pres_banca_inclinado.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(154, 6, 'pres banca', 'pecho/presbanca.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(155, 7, 'Cuadriceps', 'piernas/Cuadriceps.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(156, 7, 'Cuadriceps manuernas', 'piernas/Cuadriceps_manuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(157, 7, 'Cuadriceps Prensa', 'piernas/Cuadriceps_Prensa.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(158, 7, 'Cuadriceps Prensa_2', 'piernas/Cuadriceps_Prensa_2.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(159, 7, 'cuadriceps pullover', 'piernas/cuadriceps_pullover.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(160, 7, 'cuadriceps sentadillas', 'piernas/cuadriceps_sentadillas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(161, 7, 'gemelos escalon', 'piernas/gemelos_escalon.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(162, 7, 'gemelos escalon sentado', 'piernas/gemelos_escalon_sentado.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(163, 7, 'gemelos prensa', 'piernas/gemelos_prensa.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(169, 8, 'bicycle crunch', 'sinpesas_abdominal/bicycle_crunch.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(170, 8, 'crunch', 'sinpesas_abdominal/crunch.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(171, 8, 'diagona plank', 'sinpesas_abdominal/diagona_plank.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(172, 8, 'kneli side plank', 'sinpesas_abdominal/kneli_side_plank.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(173, 8, 'plank', 'sinpesas_abdominal/plank.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(174, 8, 'reverse crunch', 'sinpesas_abdominal/reverse_crunch.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(175, 8, 'side plank', 'sinpesas_abdominal/side_plank.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(176, 8, 'side plank reach', 'sinpesas_abdominal/side_plank_reach.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(177, 8, 'sit up', 'sinpesas_abdominal/sit_up.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(179, 9, 'horcestance', 'sinpesas_espalda/horcestance.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(180, 9, 'superman', 'sinpesas_espalda/superman.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(181, 9, 'wraise', 'sinpesas_espalda/wraise.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(182, 9, 'yraise', 'sinpesas_espalda/yraise.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(183, 10, 'box jump', 'sinpesas_piernas_y_gluteos/box_jump.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(184, 10, 'but bridge', 'sinpesas_piernas_y_gluteos/but_bridge.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(185, 10, 'lunge', 'sinpesas_piernas_y_gluteos/lunge.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(186, 10, 'one led rdl', 'sinpesas_piernas_y_gluteos/one_led_rdl.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(187, 10, 'side hip abduct', 'sinpesas_piernas_y_gluteos/side_hip_abduct.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(188, 10, 'side lunge', 'sinpesas_piernas_y_gluteos/side_lunge.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(189, 10, 'side skate jump', 'sinpesas_piernas_y_gluteos/side_skate_jump.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(190, 10, 'squat', 'sinpesas_piernas_y_gluteos/squat.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(191, 10, 'step up', 'sinpesas_piernas_y_gluteos/step_up.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(192, 10, 'wall sit', 'sinpesas_piernas_y_gluteos/wall_sit.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(193, 11, 'High knees', 'sinpesas_todo_el_cuerpo/High_knees.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(194, 11, 'inchworm', 'sinpesas_todo_el_cuerpo/inchworm.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(195, 11, 'jumping jack', 'sinpesas_todo_el_cuerpo/jumping_jack.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(196, 11, 'jump rope', 'sinpesas_todo_el_cuerpo/jump_rope.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(197, 11, 'squat jump', 'sinpesas_todo_el_cuerpo/squat_jump.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(198, 12, 'chin up', 'sinpesas_tronco/chin_up.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(199, 12, 'dip', 'sinpesas_tronco/dip.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(200, 12, 'pushup', 'sinpesas_tronco/pushup.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(201, 12, 'wallpush', 'sinpesas_tronco/wallpush.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(202, 12, 'wallslide', 'sinpesas_tronco/wallslide.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
/*!40000 ALTER TABLE `ejercicios` ENABLE KEYS */;

-- Volcando estructura para tabla gym.grupos
CREATE TABLE IF NOT EXISTS `grupos` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `grupo` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla gym.grupos: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `grupos` DISABLE KEYS */;
INSERT INTO `grupos` (`id`, `grupo`, `created_at`, `updated_at`) VALUES
	(1, 'abdominales', '2018-05-23 17:32:22', '2018-05-23 17:32:22');
INSERT INTO `grupos` (`id`, `grupo`, `created_at`, `updated_at`) VALUES
	(2, 'bíceps', '2018-05-23 17:32:46', '2018-05-23 17:32:46');
INSERT INTO `grupos` (`id`, `grupo`, `created_at`, `updated_at`) VALUES
	(3, 'tríceps', '2018-05-23 17:33:30', '2018-05-23 17:33:30');
INSERT INTO `grupos` (`id`, `grupo`, `created_at`, `updated_at`) VALUES
	(4, 'espalda', '2018-05-23 17:33:48', '2018-05-23 17:33:48');
INSERT INTO `grupos` (`id`, `grupo`, `created_at`, `updated_at`) VALUES
	(5, 'hombro', '2018-05-23 17:34:02', '2018-05-23 17:34:02');
INSERT INTO `grupos` (`id`, `grupo`, `created_at`, `updated_at`) VALUES
	(6, 'pecho', '2018-05-23 17:34:15', '2018-05-23 17:34:15');
INSERT INTO `grupos` (`id`, `grupo`, `created_at`, `updated_at`) VALUES
	(7, 'piernas', '2018-05-23 17:34:23', '2018-05-23 17:34:24');
INSERT INTO `grupos` (`id`, `grupo`, `created_at`, `updated_at`) VALUES
	(8, 'sin pesas abdominal', '2018-05-23 17:35:03', '2018-05-23 17:35:03');
INSERT INTO `grupos` (`id`, `grupo`, `created_at`, `updated_at`) VALUES
	(9, 'sin pesas espald', '2018-05-23 17:35:11', '2018-05-23 17:35:11');
INSERT INTO `grupos` (`id`, `grupo`, `created_at`, `updated_at`) VALUES
	(10, 'sin pesas piernas', '2018-05-23 17:35:53', '2018-05-23 17:35:53');
INSERT INTO `grupos` (`id`, `grupo`, `created_at`, `updated_at`) VALUES
	(11, 'sin pesas todo el cuerpo', '2018-05-23 17:36:03', '2018-05-23 17:36:03');
INSERT INTO `grupos` (`id`, `grupo`, `created_at`, `updated_at`) VALUES
	(12, 'sin pesas tronco', '2018-05-23 17:36:37', '2018-05-23 17:36:37');
/*!40000 ALTER TABLE `grupos` ENABLE KEYS */;

-- Volcando estructura para tabla gym.modalidades
CREATE TABLE IF NOT EXISTS `modalidades` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `nombre` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla gym.modalidades: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `modalidades` DISABLE KEYS */;
INSERT INTO `modalidades` (`id`, `nombre`, `created_at`, `updated_at`) VALUES
	(1, 'definir', '2018-05-23 17:40:51', '2018-05-23 17:40:51');
INSERT INTO `modalidades` (`id`, `nombre`, `created_at`, `updated_at`) VALUES
	(2, 'mantener', '2018-05-23 17:41:04', '2018-05-23 17:41:04');
INSERT INTO `modalidades` (`id`, `nombre`, `created_at`, `updated_at`) VALUES
	(3, 'muscular', '2018-05-23 17:41:34', '2018-05-23 17:41:34');
INSERT INTO `modalidades` (`id`, `nombre`, `created_at`, `updated_at`) VALUES
	(4, 'resistencia', '2018-05-23 17:41:45', '2018-05-23 17:41:46');
INSERT INTO `modalidades` (`id`, `nombre`, `created_at`, `updated_at`) VALUES
	(5, 'estiramientos', '2018-05-23 17:41:58', '2018-05-23 17:41:58');
/*!40000 ALTER TABLE `modalidades` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
