-- --------------------------------------------------------
-- Host:                         localhost
-- Versión del servidor:         5.7.19 - MySQL Community Server (GPL)
-- SO del servidor:              Win64
-- HeidiSQL Versión:             9.4.0.5125
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Volcando estructura de base de datos para gym
CREATE DATABASE IF NOT EXISTS `gym` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci */;
USE `gym`;

-- Volcando estructura para tabla gym.ejercicios
CREATE TABLE IF NOT EXISTS `ejercicios` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `id_grupo` int(10) unsigned NOT NULL,
  `ejercicio` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `id_modalidad` int(10) unsigned NOT NULL,
  `imagen` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `explicacion` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tiempo` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `material` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `posicion` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `consejo` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ejercicios_id_grupo_foreign` (`id_grupo`),
  KEY `ejercicios_id_modalidad_foreign` (`id_modalidad`),
  CONSTRAINT `ejercicios_id_grupo_foreign` FOREIGN KEY (`id_grupo`) REFERENCES `grupos` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ejercicios_id_modalidad_foreign` FOREIGN KEY (`id_modalidad`) REFERENCES `modalidads` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=203 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla gym.ejercicios: ~140 rows (aproximadamente)
/*!40000 ALTER TABLE `ejercicios` DISABLE KEYS */;
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `id_modalidad`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(57, 1, 'abdominales banco multipower', 3, 'abdominales/abdominales_banco_multipower.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(58, 1, 'abdominales como flexiones', 3, 'abdominales/abdominales_como_flexiones.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(59, 1, 'abdominales con banco', 1, 'abdominales/abdominales_con_banco.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(60, 1, 'abdominales con remo', 3, 'abdominales/abdominales_con_remo.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(61, 1, 'abdominales cuadriceps', 3, 'abdominales/abdominales_cuadriceps.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(62, 1, 'abdominales inferiro', 1, 'abdominales/abdominales_inferiro.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(63, 1, 'abdominales maquina', 3, 'abdominales/abdominales_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(64, 1, 'abdominales pies elebados', 3, 'abdominales/abdominales_pies_elebados.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(65, 1, 'abdominales polea', 3, 'abdominales/abdominales_polea.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(66, 1, 'abdominales polea triceps', 3, 'abdominales/abdominales_polea_triceps.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(67, 1, 'abdominales superior', 1, 'abdominales/abdominales_superior.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(68, 1, 'oblicuos', 3, 'abdominales/oblicuos.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(69, 1, 'oblicuos pres banca', 3, 'abdominales/oblicuos_pres_banca.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(70, 1, 'oblicuos tradicional', 3, 'abdominales/oblicuos_tradicional.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(71, 2, 'curl biceps', 2, 'biceps/curl_biceps.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(72, 2, 'curl biceps aberto', 3, 'biceps/curl_biceps_aberto.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(73, 2, 'curl biceps maquina', 3, 'biceps/curl_biceps_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(74, 2, 'curl biceps polea', 3, 'biceps/curl_biceps_polea.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(75, 2, 'curl concentrado', 3, 'biceps/curl_concentrado.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(76, 2, 'curl concentrado cerrado', 3, 'biceps/curl_concentrado_cerrado.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(77, 2, 'curl concentrado depie', 1, 'biceps/curl_concentrado_depie.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(78, 2, 'curl concentrado maquina', 3, 'biceps/curl_concentrado_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(79, 2, 'curl concentrado multiPower', 3, 'biceps/curl_concentrado_multiPower.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(80, 2, 'curl concentrado multiPower abierto', 3, 'biceps/curl_concentrado_multiPower_abierto.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(81, 2, 'curl concentrado rodila', 3, 'biceps/curl_concentrado_rodila.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(82, 2, 'curl con mancuernas', 1, 'biceps/curl_con_mancuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(83, 2, 'curl con polea', 3, 'biceps/curl_con_polea.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(84, 2, 'curl con polea barra recta', 3, 'biceps/curl_con_polea_barra_recta.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(85, 2, 'curl estiramiento', 3, 'biceps/curl_estiramiento.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(86, 2, 'curl martillo', 2, 'biceps/curl_martillo.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(87, 2, 'curl martillo depie', 2, 'biceps/curl_martillo_depie.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(88, 3, 'triceps concentrado maquina', 3, 'triceps/triceps_concentrado_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(89, 3, 'triceps concentrado maquina barra v', 2, 'triceps/triceps_concentrado_maquina_barra_v.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(90, 3, 'triceps concentrado maquina un brazo', 2, 'triceps/triceps_concentrado_maquina_un_brazo.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(91, 3, 'triceps fondos entre bancos', 2, 'triceps/triceps_fondos_entre_bancos.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(92, 3, 'triceps fondos maquina', 2, 'triceps/triceps_fondos_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(93, 3, 'triceps pajaritos', 1, 'triceps/triceps_pajaritos.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(94, 3, 'triceps pajaritos un brazo', 2, 'triceps/triceps_pajaritos_un_brazo.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(95, 3, 'triceps presbanca', 2, 'triceps/triceps_presbanca.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(96, 3, 'triceps presbanca dos mancuernas', 2, 'triceps/triceps_presbanca_dos_mancuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(97, 3, 'triceps presbanca multipower', 3, 'triceps/triceps_presbanca_multipower.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(98, 3, 'triceps sentado dos brazos una mancuerna', 3, 'triceps/triceps_sentado_dos_brazos_una_mancuerna.p', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(99, 3, 'triceps sentado un brazos una mancuerna', 3, 'triceps/triceps_sentado_un_brazos_una_mancuerna.pn', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(100, 4, 'espalda banco', 1, 'espalda/espalda_banco.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(101, 4, 'espalda barra multipower', 1, 'espalda/espalda_barra_multipower.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(102, 4, 'espalda biceps_polea', 1, 'espalda/espalda_biceps_polea.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(103, 4, 'espalda discos', 1, 'espalda/espalda_discos.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(104, 4, 'espalda dominadas', 2, 'espalda/espalda_dominadas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(105, 4, 'espalda dominadas maquina', 2, 'espalda/espalda_dominadas_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(106, 4, 'espalda exterior barra multipower', 2, 'espalda/espalda_exterior_barra_multipower.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(107, 4, 'espalda mancuernas', 2, 'espalda/espalda_mancuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(108, 4, 'espalda polea brazos estirados', 1, 'espalda/espalda_polea_brazos_estirados.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(109, 4, 'espalda polea delante', 2, 'espalda/espalda_polea_delante.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(110, 4, 'espalda polea detras', 2, 'espalda/espalda_polea_detras.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(111, 4, 'espalda remo cerrado', 1, 'espalda/espalda_remo_cerrado.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(112, 5, 'Hombro', 1, 'hombros/Hombro.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(113, 5, 'Hombro aperturas', 2, 'hombros/Hombro_aperturas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(114, 5, 'Hombro aperturas banco lateral', 1, 'hombros/Hombro_aperturas_banco_lateral.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(115, 5, 'Hombro aperturas inclinado', 1, 'hombros/Hombro_aperturas_inclinado.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(116, 5, 'Hombro aperturas polea', 1, 'hombros/Hombro_aperturas_polea.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(117, 5, 'Hombro deltoides', 1, 'hombros/Hombro_deltoides.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(118, 5, 'Hombro deltoides mancuernas', 3, 'hombros/Hombro_deltoides_mancuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(119, 5, 'Hombro deltoides maquina', 3, 'hombros/Hombro_deltoides_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(120, 5, 'Hombro elebaciones', 1, 'hombros/Hombro_elebaciones.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(121, 5, 'Hombro elebaciones polea', 3, 'hombros/Hombro_elebaciones_polea.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(122, 5, 'Hombro elebaciones una a una', 1, 'hombros/Hombro_elebaciones_una_a_una.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(123, 5, 'Hombro pajaritos', 1, 'hombros/Hombro_pajaritos.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(124, 5, 'Hombro', 2, 'hombros/Hombro.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(125, 5, 'Hombro aperturas', 2, 'hombros/Hombro_aperturas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(126, 5, 'Hombro aperturas banco lateral', 1, 'hombros/Hombro_aperturas_banco_lateral.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(127, 5, 'Hombro aperturas inclinado', 1, 'hombros/Hombro_aperturas_inclinado.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(128, 5, 'Hombro aperturas polea', 2, 'hombros/Hombro_aperturas_polea.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(129, 5, 'Hombro deltoides', 2, 'hombros/Hombro_deltoides.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(130, 5, 'Hombro deltoides mancuernas', 3, 'hombros/Hombro_deltoides_mancuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(131, 5, 'Hombro deltoides maquina', 1, 'hombros/Hombro_deltoides_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(132, 5, 'Hombro elebaciones', 3, 'hombros/Hombro_elebaciones.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(133, 5, 'Hombro elebaciones polea', 1, 'hombros/Hombro_elebaciones_polea.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(134, 5, 'Hombro elebaciones una a una', 3, 'hombros/Hombro_elebaciones_una_a_una.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(135, 5, 'Hombro pajaritos', 2, 'hombros/Hombro_pajaritos.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(136, 6, 'pecho aperturas', 2, 'pecho/pecho_aperturas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(137, 6, 'pecho aperturas mancuernas', 3, 'pecho/pecho_aperturas_mancuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(138, 6, 'pecho aperturas maquina', 1, 'pecho/pecho_aperturas_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(139, 6, 'pecho aperturas poleas', 2, 'pecho/pecho_aperturas_poleas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(140, 6, 'pecho concentrado', 2, 'pecho/pecho_concentrado.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(141, 6, 'pecho dominadas', 3, 'pecho/pecho_dominadas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(142, 6, 'pecho_flexiones', 2, 'pecho/pecho_flexiones.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(143, 6, 'pecho inclinado mancuernas', 2, 'pecho/pecho_inclinado_mancuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(144, 6, 'pecho inclinado polea', 3, 'pecho/pecho_inclinado_polea.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(145, 6, 'pecho maquina', 1, 'pecho/pecho_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(146, 6, 'pecho maquina concentrado', 1, 'pecho/pecho_maquina_concentrado.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(147, 6, 'pecho pesolibre', 1, 'pecho/pecho_pesolibre.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(148, 6, 'pecho peso frances', 3, 'pecho/pecho_peso_frances.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(149, 6, 'pecho poleas', 2, 'pecho/pecho_poleas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(150, 6, 'pecho presbanca', 1, 'pecho/pecho_presbanca.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(151, 6, 'pecho presbanca inclinado mancuernas', 1, 'pecho/pecho_presbanca_inclinado_mancuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(152, 6, 'pecho presbanca mancuernas', 2, 'pecho/pecho_presbanca_mancuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(153, 6, 'pecho pres banca inclinado', 1, 'pecho/pecho_pres_banca_inclinado.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(154, 6, 'presbanca', 2, 'pecho/presbanca.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(155, 7, 'Cuadriceps', 1, 'piernas/Cuadriceps.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(156, 7, 'Cuadriceps manuernas', 2, 'piernas/Cuadriceps_manuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(157, 7, 'Cuadriceps Prensa', 1, 'piernas/Cuadriceps_Prensa.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(158, 7, 'Cuadriceps Prensa 2', 2, 'piernas/Cuadriceps_Prensa_2.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(159, 7, 'cuadriceps pullover', 2, 'piernas/cuadriceps_pullover.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(160, 7, 'cuadriceps sentadillas', 3, 'piernas/cuadriceps_sentadillas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(161, 7, 'gemelos escalon', 3, 'piernas/gemelos_escalon.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(162, 7, 'gemelos escalon sentado', 2, 'piernas/gemelos_escalon_sentado.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(163, 7, 'gemelos_prensa', 2, 'piernas/gemelos_prensa.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(169, 8, 'bicycle crunch', 3, 'sinpesas_abdominal/bicycle_crunch.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(170, 8, 'crunch', 5, 'sinpesas_abdominal/crunch.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(171, 8, 'diagona plank', 5, 'sinpesas_abdominal/diagona_plank.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(172, 8, 'kneli side plank', 5, 'sinpesas_abdominal/kneli_side_plank.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(173, 8, 'plank', 5, 'sinpesas_abdominal/plank.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(174, 8, 'reverse crunch', 5, 'sinpesas_abdominal/reverse_crunch.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(175, 8, 'side plank', 5, 'sinpesas_abdominal/side_plank.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(176, 8, 'side plank reach', 5, 'sinpesas_abdominal/side_plank_reach.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(177, 8, 'sit up', 5, 'sinpesas_abdominal/sit_up.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(179, 9, 'horcestance', 5, 'sinpesas_espalda/horcestance.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(180, 9, 'superman', 5, 'sinpesas_espalda/superman.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(181, 9, 'wraise', 5, 'sinpesas_espalda/wraise.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(182, 9, 'yraise', 5, 'sinpesas_espalda/yraise.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(183, 10, 'box jump', 5, 'sinpesas_piernas_y_gluteos/box_jump.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(184, 10, 'but bridge', 5, 'sinpesas_piernas_y_gluteos/but_bridge.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(185, 10, 'lunge', 5, 'sinpesas_piernas_y_gluteos/lunge.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(186, 10, 'one led rdl', 5, 'sinpesas_piernas_y_gluteos/one_led_rdl.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(187, 10, 'side hip abduct', 5, 'sinpesas_piernas_y_gluteos/side_hip_abduct.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(188, 10, 'side lunge', 5, 'sinpesas_piernas_y_gluteos/side_lunge.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(189, 10, 'side skate jump', 5, 'sinpesas_piernas_y_gluteos/side_skate_jump.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(190, 10, 'squat', 5, 'sinpesas_piernas_y_gluteos/squat.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(191, 10, 'step up', 5, 'sinpesas_piernas_y_gluteos/step_up.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(192, 10, 'wall sit', 5, 'sinpesas_piernas_y_gluteos/wall_sit.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(193, 11, 'High knees', 5, 'sinpesas_todo_el_cuerpo/High_knees.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(194, 11, 'inchworm', 5, 'sinpesas_todo_el_cuerpo/inchworm.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(195, 11, 'jumping jack', 5, 'sinpesas_todo_el_cuerpo/jumping_jack.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(196, 11, 'jump rope', 5, 'sinpesas_todo_el_cuerpo/jump_rope.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(197, 11, 'squat jump', 5, 'sinpesas_todo_el_cuerpo/squat_jump.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(198, 12, 'chin up', 5, 'sinpesas_tronco/chin_up.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(199, 12, 'dip', 5, 'sinpesas_tronco/dip.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(200, 12, 'pushup', 5, 'sinpesas_tronco/pushup.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(201, 12, 'wallpush', 5, 'sinpesas_tronco/wallpush.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(202, 12, 'wallslide', 5, 'sinpesas_tronco/wallslide.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL);
/*!40000 ALTER TABLE `ejercicios` ENABLE KEYS */;

-- Volcando estructura para tabla gym.entrenos
CREATE TABLE IF NOT EXISTS `entrenos` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla gym.entrenos: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `entrenos` DISABLE KEYS */;
/*!40000 ALTER TABLE `entrenos` ENABLE KEYS */;

-- Volcando estructura para tabla gym.grupos
CREATE TABLE IF NOT EXISTS `grupos` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `grupo` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla gym.grupos: ~12 rows (aproximadamente)
/*!40000 ALTER TABLE `grupos` DISABLE KEYS */;
INSERT INTO `grupos` (`id`, `grupo`, `created_at`, `updated_at`) VALUES
	(1, 'abdominales', '2018-05-23 17:32:22', '2018-05-23 17:32:22'),
	(2, 'bíceps', '2018-05-23 17:32:46', '2018-05-23 17:32:46'),
	(3, 'tríceps', '2018-05-23 17:33:30', '2018-05-23 17:33:30'),
	(4, 'espalda', '2018-05-23 17:33:48', '2018-05-23 17:33:48'),
	(5, 'hombro', '2018-05-23 17:34:02', '2018-05-23 17:34:02'),
	(6, 'pecho', '2018-05-23 17:34:15', '2018-05-23 17:34:15'),
	(7, 'piernas', '2018-05-23 17:34:23', '2018-05-23 17:34:24'),
	(8, 'sin pesas abdominal', '2018-05-23 17:35:03', '2018-05-23 17:35:03'),
	(9, 'sin pesas espald', '2018-05-23 17:35:11', '2018-05-23 17:35:11'),
	(10, 'sin pesas piernas', '2018-05-23 17:35:53', '2018-05-23 17:35:53'),
	(11, 'sin pesas todo el cuerpo', '2018-05-23 17:36:03', '2018-05-23 17:36:03'),
	(12, 'sin pesas tronco', '2018-05-23 17:36:37', '2018-05-23 17:36:37');
/*!40000 ALTER TABLE `grupos` ENABLE KEYS */;

-- Volcando estructura para tabla gym.migrations
CREATE TABLE IF NOT EXISTS `migrations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla gym.migrations: ~6 rows (aproximadamente)
/*!40000 ALTER TABLE `migrations` DISABLE KEYS */;
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
	(6, '2014_10_12_000000_create_users_table', 1),
	(7, '2014_10_12_100000_create_password_resets_table', 1),
	(8, '2018_05_29_194640_create_grupos_table', 1),
	(9, '2018_05_29_210341_create_modalidades_table', 1),
	(10, '2018_05_30_161824_create_entrenos_table', 1),
	(11, '2018_05_31_161725_create_ejercicios_table', 1);
/*!40000 ALTER TABLE `migrations` ENABLE KEYS */;

-- Volcando estructura para tabla gym.modalidads
CREATE TABLE IF NOT EXISTS `modalidads` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `nombre` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla gym.modalidads: ~5 rows (aproximadamente)
/*!40000 ALTER TABLE `modalidads` DISABLE KEYS */;
INSERT INTO `modalidads` (`id`, `nombre`, `created_at`, `updated_at`) VALUES
	(1, 'definir', '2018-05-23 17:40:51', '2018-05-23 17:40:51'),
	(2, 'mantener', '2018-05-23 17:41:04', '2018-05-23 17:41:04'),
	(3, 'muscular', '2018-05-23 17:41:34', '2018-05-23 17:41:34'),
	(4, 'resistencia', '2018-05-23 17:41:45', '2018-05-23 17:41:46'),
	(5, 'estiramientos', '2018-05-23 17:41:58', '2018-05-23 17:41:58');
/*!40000 ALTER TABLE `modalidads` ENABLE KEYS */;

-- Volcando estructura para tabla gym.password_resets
CREATE TABLE IF NOT EXISTS `password_resets` (
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  KEY `password_resets_email_index` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla gym.password_resets: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `password_resets` DISABLE KEYS */;
/*!40000 ALTER TABLE `password_resets` ENABLE KEYS */;

-- Volcando estructura para tabla gym.users
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `apellido` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dob` date NOT NULL,
  `sexo` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla gym.users: ~1 rows (aproximadamente)
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` (`id`, `name`, `apellido`, `email`, `password`, `dob`, `sexo`, `remember_token`, `created_at`, `updated_at`) VALUES
	(1, 'raziel', 'Veizaga', 'narutoonline877@gmail.com', '$2y$10$C.zO2jxmAYTIyjN2rlP5zu54H6lSN7Uy2CTlAtHpMtF1IEZ7HMrA2', '1997-09-07', 'mujer', 'wRofxHRfZAJpr0IlUHEVudsNDthWOQ93tDCUNqCN6Gl7UHB55Jj2FdswwD1X', '2018-05-31 16:32:26', '2018-05-31 16:32:26');
/*!40000 ALTER TABLE `users` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
